name: discordbotadminui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  http: ^0.13.4
  dropdown_button2: 1.6.3
  provider: 6.0.3
  expandable: 5.0.1
  flutter_colorpicker: 1.0.3
  flutter_expanded_tile: ^0.3.6
  google_fonts: 3.0.1
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  sentry_flutter: ^6.18.1
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.4
  get_it: ^7.2.0
  intl: ^0.17.0
  injectable: ^2.1.0
  package_info_plus: ^3.0.2 
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 5.0.3
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/maxresdefault.png
